config/routes.rb
Rails.application.routes.draw do
  get 'answers/create'

  root 'application#home'
  resources :books, only: [:new, :create, :show, :index] do
    resources :questions, only: [:show] do
      resources :answers, only: [:create]
    end
    get '/questions/:id/next', to: 'questions#next', as: :next_question
  end

  resources :answers
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :questions
  accepts_nested_attributes_for :questions

  def questions_attributes=(hash)
    hash.each do |k, v|
      self.questions.build(content: v[:content])
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :book
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    question = Question.find(params[:question_id])
    answer = question.answers.build(answer_params)
    
    if answer.save
      question.book.questions.last == question ? (redirect_to book_path(params[:book_id])) : (redirect_to book_next_question_path(params[:book_id], question))
    end
  end

  private
    def answer_params
      params.require(:answer).permit(:content)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def home
    render :'layouts/home'
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
    @book.questions.build
  end

  def index 
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.save
    redirect_to book_path(@book)
  end

  def show
    @book = Book.find(params[:id])
  end

  private
    def book_params
      params.require(:book).permit(:title, :creator, :questions_attributes => [:content])
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def show
    @book = Book.find(params[:book_id])
    @question = Question.find(params[:id])
  end
  
  def next
    @book = Book.find(params[:book_id])
    @question = Question.find(params[:id])
    next_question = @book.questions.where('id > ?', @question.id).first
    redirect_to book_question_path(@book, next_question)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/books/index.html.erb
<% @books.each do |book| %>
  <h3><%= link_to book.title, book_path(book) %></h3>
<% end %>

app/views/books/new.html.erb
<h1>Create a New Book</h1>
<%= form_for @book do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %> <br />
  <%= f.label :creator %>
  <%= f.text_field :creator %> <br />
  <div id="questions">
    <%= f.fields_for :questions do |question_form| %>
      <%= question_form.text_field :content %>
    <% end %>
  </div>
  <button id="add-question">Add Question</button>
  <%= f.submit %>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<%= link_to "Start", book_question_path(@book, @book.questions.first) %>

<ul>
  <% @book.questions.each do |question| %>
    <li>
      <%= question.content %>
      <ul>
        <% question.answers.each do |answer| %>
          <li><%= answer.content %></li>
        <% end %>
      </ul>
    </li>
    
  <% end %>
</ul>

app/views/layouts/_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'New Book', new_book_path %></li>
    <li><%= link_to 'Curent Books', books_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SlamBookRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/questions/show.html.erb
<h1><%= @book.title %></h1>
<%= @question.content %> <br/>
<%= form_for ([@book, @question, Answer.new]) do |f| %>
  <%= f.text_field :content %>
  <% if @book.questions.last == @question %>
    <%= f.submit "Complete" %>
  <% else %>
  <%= f.submit "Next Question" %>
  <% end %>
<% end %>